# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI

on: [push]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        cache: 'poetry'
    - name: Install dependencies
      run: |
        poetry install -E all
    - name: Test with pytest
      run: |
        poetry run pytest
    - name: Lint with black, isort, and ruff
      run: |
        poetry run black --check geometricalgebra/
        poetry run isort --check geometricalgebra/
    - name: Type checking with mypy
      run: |
        pip install mypy
        mypy
